Hw2
prefabsprout/selenium_course pull request #1
Opened 2021-05-31 08:11 UTC by prefabsprout

2021-06-01 12:50 UTC, zhidelev requested changes

2021-06-01 12:50 UTC, zhidelev commented on test/HW2/conftest.py
> +    return driver
Лучше делать `yield driver`, а после его закрывать, а не делать `close()` в тесте.

2021-06-01 12:50 UTC, zhidelev commented on test/HW2/locators/different_elements_locators.py
> +class DifferentElementsLocators:
Лучше разделить локаторы в классы Checkbox, Radiobutton, Log, а не объединятть их в класс с именем DifferentElementsLocators (слишком общее имя).

2021-06-01 12:50 UTC, zhidelev commented on test/HW2/test_exercise_1.py
> +    driver.get(url="https://jdi-testing.github.io/jdi-light/index.html")
Вынести URL в констанут и использовать через импорт.

2021-06-01 12:50 UTC, zhidelev commented on test/HW2/test_exercise_1.py
> +    driver.find_element(*JdiTestingLocators.LOGIN_BUTTON).click()
Думаю, что этот код можно вынести в модуль `functions.py` например и объединить в функцию `login()` и использовать в тесте.

2021-06-01 12:50 UTC, zhidelev commented on test/HW2/test_exercise_1.py
> +    # 4.Assert Username is loggined
Typo loggined -> logged

2021-06-01 12:50 UTC, zhidelev commented on test/HW2/test_exercise_1.py
> +    assert iframes_with_frame_button != []
Возможно лучше переписать:
```
assert driver.find_elements_by_id("frame")
```

2021-06-01 12:50 UTC, zhidelev commented on test/HW2/test_exercise_1.py
> +def test_exercise_1(user_credentials, driver):
Назвать функцию более понятно согласно тому, что в ней тестируется.

2021-06-01 12:50 UTC, zhidelev commented on test/HW2/test_exercise_2.py
> +def test_exercise_2(user_credentials, driver):
Назвать функцию более понятно согласно тому, что в ней тестируется.

2021-06-01 12:54 UTC, prefabsprout commented on test/HW2/test_exercise_1.py
> +    driver.find_element(*JdiTestingLocators.LOGIN_BUTTON).click()
Я предполагал вынести это в отдельный метод на третьей домашке. Там как раз надо реализовать page object. А тут я подумал, что домашка требует более "влобную" реализацию на чистом селениуме

2021-06-01 12:57 UTC, prefabsprout commented on test/HW2/test_exercise_1.py
> +    assert iframes_with_frame_button != []
Я подумал, что поместить это в переменную лучше из соображений читаемости. Условие домашки потребовало найти фреймы с frame button. Из описания локатора сложно сказать, что это именно локаторы с этой кнопкой. Но это они

2021-06-01 13:03 UTC, prefabsprout commented
И да, пояснение по поводу последнего коммита (который Rearrange project structure). Я решил так сделать, поскольку остальные домашние работы подразумевают рефакторинг уже написанной "наивной" реализации. Исходя из этого и из того, что у нас ветки, я не вижу смысла нагромождать репозиторий папками - ведь домашки будут рассортированы по веткам.

2021-06-01 13:35 UTC, prefabsprout commented on test/HW2/test_exercise_1.py
> +    assert iframes_with_frame_button != []
Но избавиться от `!= []` точно надо, согласен, это косяк. Избавлюсь, как только получу комментарий насчёт моей мысли оставить список из элементов в переменной

2021-06-04 09:40 UTC, zhidelev commented on test/HW2/test_exercise_1.py
> +    assert iframes_with_frame_button != []
Я не верен, что flake8 не будет ругаться на этот код, если переменная больше нигде не используется. Попробуй запустить flake8 на этот код, если не ругается, то оставляй испльзование переменной 👍

2021-06-04 09:55 UTC, zhidelev requested changes
Поправить пару комментариев 🙂

2021-06-04 09:55 UTC, zhidelev commented on test/Locators/buttons.py
> +    SERVICE_DROPDOWN_BUTTON = (By.CSS_SELECTOR, ".uui-header .nav > li:nth-child(3) > a")
Может стоит их ещё разделить на кнопки из `Header` и `Sidebar`?

2021-06-04 09:55 UTC, zhidelev commented on test/test_main_page_layout.py
> +    assert driver.find_element(*Icons.ICON_MULTI).is_displayed() is True
Необязательно делать `assert ... is True`, можно просто `assert ...`

2021-06-04 09:59 UTC, prefabsprout commented on test/HW2/test_exercise_1.py
> +    assert iframes_with_frame_button != []
flake8 ругается только на длину строк:
```
>flake8 test
test\test_different_elements_page_functionality.py:23:80: E501 line too long (86 > 79 characters)
test\test_different_elements_page_functionality.py:24:80: E501 line too long (90 > 79 characters)
test\test_different_elements_page_functionality.py:28:80: E501 line too long (97 > 79 characters)
test\test_different_elements_page_functionality.py:37:80: E501 line too long (83 > 79 characters)
test\test_different_elements_page_functionality.py:41:80: E501 line too long (84 > 79 characters)
test\test_different_elements_page_functionality.py:46:80: E501 line too long (81 > 79 characters)
test\test_different_elements_page_functionality.py:49:80: E501 line too long (86 > 79 characters)
test\test_different_elements_page_functionality.py:52:80: E501 line too long (83 > 79 characters)
test\test_main_page_layout.py:17:80: E501 line too long (86 > 79 characters)
test\test_main_page_layout.py:18:80: E501 line too long (90 > 79 characters)
test\test_main_page_layout.py:22:80: E501 line too long (97 > 79 characters)
test\test_main_page_layout.py:24:80: E501 line too long (100 > 79 characters)
test\test_main_page_layout.py:26:80: E501 line too long (83 > 79 characters)
test\test_main_page_layout.py:27:80: E501 line too long (82 > 79 characters)
test\test_main_page_layout.py:28:80: E501 line too long (87 > 79 characters)
test\test_main_page_layout.py:36:80: E501 line too long (93 > 79 characters)
test\test_main_page_layout.py:37:80: E501 line too long (99 > 79 characters)
test\test_main_page_layout.py:38:80: E501 line too long (99 > 79 characters)
test\test_main_page_layout.py:39:80: E501 line too long (82 > 79 characters)
test\test_main_page_layout.py:40:80: E501 line too long (90 > 79 characters)
test\test_main_page_layout.py:41:80: E501 line too long (80 > 79 characters)
test\test_main_page_layout.py:42:80: E501 line too long (86 > 79 characters)
test\test_main_page_layout.py:43:80: E501 line too long (92 > 79 characters)
test\test_main_page_layout.py:44:80: E501 line too long (92 > 79 characters)
test\test_main_page_layout.py:45:80: E501 line too long (94 > 79 characters)
test\test_main_page_layout.py:46:80: E501 line too long (83 > 79 characters)
test\test_main_page_layout.py:52:80: E501 line too long (81 > 79 characters)
test\test_main_page_layout.py:59:80: E501 line too long (98 > 79 characters)
test\test_main_page_layout.py:61:80: E501 line too long (91 > 79 characters)
test\test_main_page_layout.py:62:80: E501 line too long (81 > 79 characters)
test\test_main_page_layout.py:63:80: E501 line too long (95 > 79 characters)
test\test_main_page_layout.py:64:80: E501 line too long (95 > 79 characters)
test\Locators\buttons.py:8:80: E501 line too long (85 > 79 characters)
test\Locators\buttons.py:9:80: E501 line too long (86 > 79 characters)
test\Locators\buttons.py:10:80: E501 line too long (83 > 79 characters)
test\Locators\buttons.py:11:80: E501 line too long (91 > 79 characters)
test\Locators\buttons.py:12:80: E501 line too long (86 > 79 characters)
test\Locators\buttons.py:13:80: E501 line too long (92 > 79 characters)
test\Locators\buttons.py:14:80: E501 line too long (93 > 79 characters)
test\Locators\buttons.py:15:80: E501 line too long (100 > 79 characters)
test\Locators\buttons.py:17:80: E501 line too long (89 > 79 characters)
test\Locators\checkboxes.py:5:80: E501 line too long (103 > 79 characters)
test\Locators\checkboxes.py:6:80: E501 line too long (102 > 79 characters)
test\Locators\dropdowns.py:5:80: E501 line too long (86 > 79 characters)
test\Locators\radiobuttons.py:5:80: E501 line too long (106 > 79 characters)
test\Locators\text_sections.py:5:80: E501 line too long (82 > 79 characters)
test\Locators\text_sections.py:6:80: E501 line too long (80 > 79 characters)
```
Но на мой взгляд пайчармовский линтер (он ругается на > 120 символов) более актуальный в контексте современных мониторов.

2021-06-07 20:19 UTC, zhidelev commented on test/HW2/test_exercise_1.py
> +    assert iframes_with_frame_button != []
Да, `E501` не критичен.

2021-06-07 20:20 UTC, zhidelev approved these changes

2021-06-08 09:37 UTC, merged