Hw3
prefabsprout/selenium_course pull request #2
Opened 2021-06-07 14:26 UTC by prefabsprout

Если что, на случай, если вдруг в HW2 ещё появятся какие-то пожелания, я просто ребейзнусь на возникшие изменения, потому, надеюсь, ничего страшного, если я уже сейчас открою ПР для HW3.

2021-06-07 14:28 UTC, prefabsprout commented
Запоздало осознал, что это не очень прилично делать такой ребейзнутый напрочь ПР (учитывая, что в нём будут в том числе и старые изменения из HW2), потому прошу прощения за это. Больше так не буду.

2021-06-07 20:16 UTC, zhidelev requested changes
Молодец 👏 
- [x] Поправить комментарии.
- [ ] Переименовать пакеты согласно https://www.python.org/dev/peps/pep-0008/#package-and-module-names

2021-06-07 20:16 UTC, zhidelev commented on test/test_main_page_layout.py
> +    home_page.should_be_authorised(user_credentials["full_username"])
Typo `authorised` -> `authorized`

2021-06-07 20:16 UTC, zhidelev commented on test/test_main_page_layout.py
> +def test_main_page_layout(user_credentials, browser):
Лучше разделить тест на несколько согласно количеству ассертов. Если ассерт в начале упадёт, то будет непонятно что с остальной частью страницы.

2021-06-07 20:16 UTC, zhidelev commented on test/test_different_elements_page_functionality.py
> +    main_page.should_be_authorised(user_credentials["full_username"])
Typo `authorised` -> `authorized`

2021-06-07 20:16 UTC, zhidelev commented on test/test_different_elements_page_functionality.py
> +def test_different_elements_page_functionality(user_credentials, browser):
Лучше разделить тест на несколько согласно количеству ассертов. Если ассерт в начале упадёт, то будет непонятно что с остальной частью страницы.

2021-06-07 20:16 UTC, zhidelev commented on test/PageObjects/base_page.py
> +        return True
`True` здесь излишен, всё равно `True` вернётся в блоге `try`, если всё хорошо.

2021-06-07 20:16 UTC, zhidelev commented on test/PageObjects/main_page.py
> +            "Unexpected text on METALS & COLORS button in header"
Можно оставить один ассерт и передавать все значения через `parametrize` в тесте.

2021-06-07 20:16 UTC, zhidelev commented on test/PageObjects/main_page.py
> +        assert self.browser.find_element(*Icons.ICON_MULTI).is_displayed(), "Multi icon is not displayed"
Можно оставить один ассерт и передавать все значения через `parametrize` в тесте.

2021-06-07 20:16 UTC, zhidelev commented on test/PageObjects/main_page.py
> +                                     "wish to get more…"), "Unexpected text under BASE icon"
Можно оставить один ассерт и передавать все значения через `parametrize` в тесте.

2021-06-07 20:16 UTC, zhidelev commented on test/PageObjects/main_page.py
> +            "Unexpected text on Elements packs button in sidebar"
Можно оставить один ассерт и передавать все значения через `parametrize` в тесте.

2021-06-09 20:00 UTC, prefabsprout commented on test/PageObjects/base_page.py
> +        return True
Не похоже, что лишний. Без него тесты падают.

2021-06-11 12:29 UTC, zhidelev commented on test/PageObjects/base_page.py
> +        return True
Да, я не обратил внимание, что в `try` нет `return` . Давай тогда не будем удалять `return True` 👍

2021-06-19 10:03 UTC, zhidelev approved these changes
Принято 👍

2021-06-19 19:22 UTC, merged